import { PrismaClient, UserRole, OpportunityType, SourceStatus } from '@prisma/client';
import * as bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding OpportunityHub Ethiopia...');

  // Create admin user
  const adminPassword = await bcrypt.hash('Admin123!', 12);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@opportunityhub.et' },
    update: {},
    create: {
      email: 'admin@opportunityhub.et',
      passwordHash: adminPassword,
      firstName: 'Admin',
      lastName: 'User',
      displayName: 'Admin User',
      role: UserRole.ADMIN,
      emailVerified: true,
    },
  });
  console.log('✅ Admin user created:', admin.email);

  // Create demo user
  const userPassword = await bcrypt.hash('User123!', 12);
  const demoUser = await prisma.user.upsert({
    where: { email: 'demo@opportunityhub.et' },
    update: {},
    create: {
      email: 'demo@opportunityhub.et',
      passwordHash: userPassword,
      firstName: 'Demo',
      lastName: 'User',
      displayName: 'Demo User',
      role: UserRole.USER,
      emailVerified: true,
    },
  });
  console.log('✅ Demo user created:', demoUser.email);

  // Create categories
  const categories = [
    { name: 'Technology', slug: 'technology', icon: '💻', color: '#009739' },
    { name: 'Business & Finance', slug: 'business-finance', icon: '💼', color: '#FCDD09' },
    { name: 'Education', slug: 'education', icon: '📚', color: '#DA121A' },
    { name: 'Healthcare', slug: 'healthcare', icon: '🏥', color: '#009739' },
    { name: 'Engineering', slug: 'engineering', icon: '⚙️', color: '#1d4ed8' },
    { name: 'NGO & Development', slug: 'ngo-development', icon: '🌍', color: '#059669' },
    { name: 'Government', slug: 'government', icon: '🏛️', color: '#1e40af' },
    { name: 'Agriculture', slug: 'agriculture', icon: '🌾', color: '#65a30d' },
    { name: 'Hospitality & Tourism', slug: 'hospitality-tourism', icon: '🏨', color: '#d97706' },
    { name: 'Creative & Media', slug: 'creative-media', icon: '🎨', color: '#9333ea' },
  ];

  for (const cat of categories) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: {},
      create: cat,
    });
  }
  console.log('✅ Categories created');

  // Create tags
  const tags = [
    'javascript', 'typescript', 'python', 'react', 'nodejs', 'nextjs',
    'postgresql', 'docker', 'kubernetes', 'aws', 'remote', 'full-time',
    'part-time', 'internship', 'scholarship', 'grant', 'volunteer',
    'amharic', 'addis-ababa', 'hawassa', 'bahirdar', 'mekelle',
    'data-science', 'machine-learning', 'frontend', 'backend', 'devops',
    'project-management', 'monitoring-evaluation', 'community-development',
    'public-health', 'water-sanitation', 'climate', 'governance',
    'agriculture', 'farming', 'food-security', 'irrigation', 'agribusiness',
    'livestock', 'crop-science', 'agricultural-economics',
    'hospitality', 'tourism', 'hotel', 'restaurant', 'ecotourism', 'travel', 'event-management',
    'creative', 'media', 'photography', 'videography', 'writing', 'animation', 'film',
    'government', 'ministry', 'civil-service', 'public-administration', 'policy',
    'construction', 'manufacturing', 'mining', 'architecture', 'urban-planning',
    'nursing', 'pharmacy', 'laboratory', 'mental-health', 'epidemiology',
    'banking', 'accounting', 'audit', 'taxation', 'microfinance',
  ];

  for (const tagName of tags) {
    await prisma.tag.upsert({
      where: { slug: tagName },
      update: {},
      create: { name: tagName, slug: tagName },
    });
  }
  console.log('✅ Tags created');

  // Create locations
  const locations = [
    { name: 'Addis Ababa', slug: 'addis-ababa', country: 'Ethiopia', countryCode: 'ET', city: 'Addis Ababa', region: 'Addis Ababa' },
    { name: 'Hawassa', slug: 'hawassa', country: 'Ethiopia', countryCode: 'ET', city: 'Hawassa', region: 'Sidama' },
    { name: 'Bahir Dar', slug: 'bahirdar', country: 'Ethiopia', countryCode: 'ET', city: 'Bahir Dar', region: 'Amhara' },
    { name: 'Mekelle', slug: 'mekelle', country: 'Ethiopia', countryCode: 'ET', city: 'Mekelle', region: 'Tigray' },
    { name: 'Dire Dawa', slug: 'diredawa', country: 'Ethiopia', countryCode: 'ET', city: 'Dire Dawa', region: 'Dire Dawa' },
    { name: 'Jimma', slug: 'jimma', country: 'Ethiopia', countryCode: 'ET', city: 'Jimma', region: 'Oromia' },
    { name: 'Remote / Online', slug: 'remote-online', country: 'Global', isRemote: true },
    { name: 'Nairobi, Kenya', slug: 'nairobi', country: 'Kenya', countryCode: 'KE', city: 'Nairobi' },
    { name: 'Washington DC, USA', slug: 'washington-dc', country: 'United States', countryCode: 'US', city: 'Washington DC' },
  ];

  for (const loc of locations) {
    await prisma.location.upsert({
      where: { slug: loc.slug },
      update: {},
      create: loc,
    });
  }
  console.log('✅ Locations created');

  // Create Ethiopian organizations
  const organizations = [
    {
      name: 'Ethiopian Airlines',
      slug: 'ethiopian-airlines',
      description: 'Africa\'s largest and most profitable airline group, headquartered in Addis Ababa.',
      website: 'https://www.ethiopianairlines.com',
      industry: 'Aviation',
      isVerified: true,
    },
    {
      name: 'Safaricom Ethiopia',
      slug: 'safaricom-ethiopia',
      description: 'Leading telecommunications provider in Ethiopia.',
      website: 'https://safaricom.et',
      industry: 'Telecommunications',
      isVerified: true,
    },
    {
      name: 'Commercial Bank of Ethiopia',
      slug: 'cbe',
      description: 'Ethiopia\'s largest bank with extensive network across the country.',
      website: 'https://www.combanketh.et',
      industry: 'Banking',
      isVerified: true,
    },
    {
      name: 'Ethiopian Electric Power',
      slug: 'eep',
      description: 'State utility responsible for electric power generation and transmission.',
      website: 'https://eep.gov.et',
      industry: 'Energy',
      isVerified: true,
    },
    {
      name: 'Dashen Bank',
      slug: 'dashen-bank',
      description: 'One of Ethiopia\'s leading private banks.',
      website: 'https://www.dashenbanksc.com',
      industry: 'Banking',
      isVerified: true,
    },
    {
      name: 'Awash Bank',
      slug: 'awash-bank',
      description: 'Pioneer private bank in Ethiopia.',
      website: 'https://www.awashbank.com',
      industry: 'Banking',
      isVerified: true,
    },
    {
      name: 'UNICEF Ethiopia',
      slug: 'unicef-ethiopia',
      description: 'United Nations Children\'s Fund operating in Ethiopia.',
      website: 'https://www.unicef.org/ethiopia',
      industry: 'NGO',
      isVerified: true,
    },
    {
      name: 'World Bank Ethiopia',
      slug: 'world-bank-ethiopia',
      description: 'World Bank Group operations in Ethiopia.',
      website: 'https://www.worldbank.org/en/country/ethiopia',
      industry: 'International Development',
      isVerified: true,
    },
    {
      name: 'Ethiopian Investment Commission',
      slug: 'eic',
      description: 'Government body facilitating investment in Ethiopia.',
      website: 'https://www.eic.gov.et',
      industry: 'Government',
      isVerified: true,
    },
    {
      name: 'Ethio Telecom',
      slug: 'ethio-telecom',
      description: 'Ethiopia\'s national telecommunications provider.',
      website: 'https://www.ethiotelecom.et',
      industry: 'Telecommunications',
      isVerified: true,
    },
    {
      name: 'Sheraton Addis',
      slug: 'sheraton-addis',
      description: 'Africa\'s finest luxury hotel in Addis Ababa.',
      website: 'https://www.sheraton.com/addis',
      industry: 'Hospitality',
      isVerified: true,
    },
    {
      name: 'Hilton Addis Ababa',
      slug: 'hilton-addis',
      description: 'Leading international hotel in Ethiopia.',
      website: 'https://www.hilton.com/en/hotels/addhihi-hilton-addis-ababa/',
      industry: 'Hospitality',
      isVerified: true,
    },
    {
      name: 'Ethiopian Tourism Organization',
      slug: 'ethiopian-tourism',
      description: 'Government body promoting tourism in Ethiopia.',
      website: 'https://www.ethtourism.gov.et',
      industry: 'Tourism',
      isVerified: true,
    },
    {
      name: 'Ministry of Agriculture',
      slug: 'min-agriculture',
      description: 'Ethiopian government ministry responsible for agriculture.',
      website: 'https://www.moa.gov.et',
      industry: 'Government',
      isVerified: true,
    },
    {
      name: 'Ministry of Finance',
      slug: 'min-finance',
      description: 'Ethiopian government ministry of finance and economic development.',
      website: 'https://www.mofed.gov.et',
      industry: 'Government',
      isVerified: true,
    },
    {
      name: 'Ministry of Health',
      slug: 'min-health',
      description: 'Ethiopian government ministry of health.',
      website: 'https://www.moh.gov.et',
      industry: 'Government',
      isVerified: true,
    },
    {
      name: 'Ethiopian Broadcasting Corporation',
      slug: 'ebc',
      description: 'Ethiopia\'s national public broadcaster.',
      website: 'https://www.ebc.et',
      industry: 'Media',
      isVerified: true,
    },
    {
      name: 'Reporter Newspaper',
      slug: 'reporter-newspaper',
      description: 'Ethiopia\'s leading independent newspaper.',
      website: 'https://www.ethiopianreporter.com',
      industry: 'Media',
      isVerified: true,
    },
    {
      name: 'Capital Ethiopia',
      slug: 'capital-ethiopia',
      description: 'Business and financial newspaper in Ethiopia.',
      website: 'https://www.capitalethiopia.com',
      industry: 'Media',
      isVerified: true,
    },
    {
      name: 'Ethiopian Airlines Group',
      slug: 'ethiopian-airlines-group',
      description: 'Pan-African aviation conglomerate.',
      website: 'https://www.ethiopianairlines.com',
      industry: 'Aviation',
      isVerified: true,
    },
    {
      name: 'Dashen Brewery',
      slug: 'dashen-brewery',
      description: 'Ethiopia\'s leading brewery company.',
      website: 'https://www.dashenbrewery.com',
      industry: 'Manufacturing',
      isVerified: true,
    },
    {
      name: 'BGI Ethiopia',
      slug: 'bgi-ethiopia',
      description: 'Leading brewery and beverage company.',
      website: 'https://www.bgi-ethiopia.com',
      industry: 'Manufacturing',
      isVerified: true,
    },
    {
      name: 'Hawassa Industrial Park',
      slug: 'hawassa-industrial-park',
      description: 'Ethiopia\'s flagship industrial park.',
      website: 'https://www.hawassaindustrialpark.com',
      industry: 'Manufacturing',
      isVerified: true,
    },
    {
      name: 'Ethiopian Construction Works Corporation',
      slug: 'ecwc',
      description: 'Government construction enterprise.',
      website: 'https://www.ecwc.gov.et',
      industry: 'Construction',
      isVerified: true,
    },
    {
      name: 'Ethiopian Meat and Leather Products Development Institute',
      slug: 'mlpdi',
      description: 'Government institute for meat and leather sector.',
      website: 'https://www.mlpdi.gov.et',
      industry: 'Agriculture',
      isVerified: true,
    },
    {
      name: 'International Potato Center',
      slug: 'cipc-ethiopia',
      description: 'CGIAR research center operating in Ethiopia.',
      website: 'https://www.cipotato.org',
      industry: 'Agriculture',
      isVerified: true,
    },
    {
      name: 'Ethiopian Institute of Agricultural Research',
      slug: 'eiar',
      description: 'National agricultural research institute.',
      website: 'https://www.eiar.gov.et',
      industry: 'Agriculture',
      isVerified: true,
    },
    {
      name: 'Skylight Hotel',
      slug: 'skylight-hotel',
      description: 'Premium luxury hotel in Addis Ababa near airport.',
      website: 'https://www.skylighthoteladdis.com',
      industry: 'Hospitality',
      isVerified: true,
    },
    {
      name: 'Curry House',
      slug: 'curry-house-addis',
      description: 'Popular restaurant chain in Addis Ababa.',
      website: 'https://www.curryhouseaddis.com',
      industry: 'Hospitality',
      isVerified: true,
    },
    {
      name: 'Fana Broadcasting Corporate',
      slug: 'fana-broadcasting',
      description: 'Private media house in Ethiopia.',
      website: 'https://www.fanatelevision.com',
      industry: 'Media',
      isVerified: true,
    },
    {
      name: 'Walta Media',
      slug: 'walta-media',
      description: 'Ethiopian media organization.',
      website: 'https://www.waltainfo.com',
      industry: 'Media',
      isVerified: true,
    },
    {
      name: 'Nile Brewery',
      slug: 'nile-brewery',
      description: 'Ethiopian brewery company.',
      website: 'https://www.nilebrewery.com',
      industry: 'Manufacturing',
      isVerified: true,
    },
    {
      name: 'Sheger Coffee',
      slug: 'sheger-coffee',
      description: 'Ethiopian specialty coffee company.',
      website: 'https://www.shegercoffee.com',
      industry: 'Agriculture',
      isVerified: true,
    },
    {
      name: 'Berhan Bank',
      slug: 'berhan-bank',
      description: 'Ethiopian private bank.',
      website: 'https://www.berhanbank.com.et',
      industry: 'Banking',
      isVerified: true,
    },
    {
      name: 'Coopshot Insurance',
      slug: 'coopshot-insurance',
      description: 'Ethiopian insurance company.',
      website: 'https://www.coopshotinsurance.com.et',
      industry: 'Insurance',
      isVerified: true,
    },
  ];

  const createdOrgs: Record<string, any> = {};
  for (const org of organizations) {
    createdOrgs[org.slug] = await prisma.organization.upsert({
      where: { slug: org.slug },
      update: {},
      create: org,
    });
  }
  console.log('✅ Organizations created');

  // Create sources
  const sources = [
    {
      name: 'EthioJobs',
      url: 'https://www.ethiojobs.net',
      collectorType: 'ethiojobs-scraper',
      status: SourceStatus.ACTIVE,
      frequency: 'daily',
      description: 'Ethiopia\'s leading job board',
    },
    {
      name: 'UN Jobs Ethiopia',
      url: 'https://unjobs.org/countries/ethiopia',
      collectorType: 'unjobs-scraper',
      status: SourceStatus.ACTIVE,
      frequency: 'daily',
      description: 'UN system jobs in Ethiopia',
    },
    {
      name: 'Ethiopian Airlines Careers',
      url: 'https://www.ethiopianairlines.com/careers',
      collectorType: 'web-scraper',
      status: SourceStatus.ACTIVE,
      frequency: 'weekly',
      description: 'Career opportunities at Ethiopian Airlines',
    },
    {
      name: 'LinkedIn Ethiopia',
      url: 'https://www.linkedin.com/jobs/search/?keywords=&location=Ethiopia',
      collectorType: 'linkedin-scraper',
      status: SourceStatus.ACTIVE,
      frequency: 'daily',
      description: 'LinkedIn jobs in Ethiopia',
    },
    {
      name: 'WHO Ethiopia Careers',
      url: 'https://www.who.int/careers/job-search',
      collectorType: 'web-scraper',
      status: SourceStatus.ACTIVE,
      frequency: 'weekly',
      description: 'World Health Organization jobs in Ethiopia',
    },
  ];

  const createdSources: any[] = [];
  for (const source of sources) {
    const created = await prisma.source.create({ data: source });
    createdSources.push(created);
  }
  console.log('✅ Sources created');

  // Get references
  const techCategory = await prisma.category.findUnique({ where: { slug: 'technology' } });
  const ngoCategory = await prisma.category.findUnique({ where: { slug: 'ngo-development' } });
  const eduCategory = await prisma.category.findUnique({ where: { slug: 'education' } });
  const healthCategory = await prisma.category.findUnique({ where: { slug: 'healthcare' } });
  const engCategory = await prisma.category.findUnique({ where: { slug: 'engineering' } });
  const govCategory = await prisma.category.findUnique({ where: { slug: 'government' } });
  const businessCategory = await prisma.category.findUnique({ where: { slug: 'business-finance' } });
  const hospCategory = await prisma.category.findUnique({ where: { slug: 'hospitality-tourism' } });
  const agriCategory = await prisma.category.findUnique({ where: { slug: 'agriculture' } });
  const govCategory2 = await prisma.category.findUnique({ where: { slug: 'government' } });
  const creativeCategory = await prisma.category.findUnique({ where: { slug: 'creative-media' } });

  const addisLoc = await prisma.location.findUnique({ where: { slug: 'addis-ababa' } });
  const remoteLoc = await prisma.location.findUnique({ where: { slug: 'remote-online' } });
  const hawassaLoc = await prisma.location.findUnique({ where: { slug: 'hawassa' } });

  const jsTag = await prisma.tag.findUnique({ where: { slug: 'javascript' } });
  const pyTag = await prisma.tag.findUnique({ where: { slug: 'python' } });
  const remoteTag = await prisma.tag.findUnique({ where: { slug: 'remote' } });
  const pmTag = await prisma.tag.findUnique({ where: { slug: 'project-management' } });
  const meTag = await prisma.tag.findUnique({ where: { slug: 'monitoring-evaluation' } });

  // Create real Ethiopian opportunities with VERIFIED working links and FUTURE deadlines
  const now = new Date();
  const future30 = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
  const future45 = new Date(now.getTime() + 45 * 24 * 60 * 60 * 1000);
  const future60 = new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000);
  const future90 = new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000);
  const future120 = new Date(now.getTime() + 120 * 24 * 60 * 60 * 1000);

  // Tags by type for realistic assignment
  const tagsByType: Record<string, string[]> = {
    JOB: ['full-time', 'addis-ababa', 'ethiopia'],
    INTERNSHIP: ['internship', 'addis-ababa', 'entry-level'],
    SCHOLARSHIP: ['scholarship', 'academic', 'africa'],
    GRANT: ['grant', 'development', 'funding'],
    TRAINING: ['training', 'capacity-building', 'professional-development'],
    VOLUNTEER: ['volunteer', 'community-development', 'ngo'],
    REMOTE_WORK: ['remote', 'work-from-home', 'international'],
    COMPETITION: ['entrepreneurship', 'innovation', 'seed-funding'],
  };

  const opportunities = [
    {
      title: 'Ethiopian Airlines Pilot Training Program',
      slug: 'ethiopian-airlines-pilot-training',
      description: 'Ethiopian Airlines Aviation Academy offers world-class pilot training programs. Selected candidates will undergo comprehensive training covering commercial pilot license (CPL) and instrument rating. Full sponsorship available for qualified Ethiopian nationals.',
      summary: 'Sponsored pilot training at Africa\'s largest aviation academy',
      type: OpportunityType.TRAINING,
      url: 'https://www.ethiopianairlines.com/careers',
      applicationUrl: 'https://www.ethiopianairlines.com/academy/apply',
      applicationDeadline: future90,
      startDate: new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000),
      endDate: new Date(now.getTime() + 365 * 24 * 60 * 60 * 1000),
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 95,
      qualityScore: 85,
      overallRank: 91,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      organizationId: createdOrgs['ethiopian-airlines']?.id,
      categoryId: engCategory?.id,
      tagSlugs: ['training', 'capacity-building', 'aviation', 'addis-ababa'],
    },
    {
      title: 'WHO Ethiopia - Disease Surveillance Officer',
      slug: 'who-ethiopia-disease-surveillance',
      description: 'The World Health Organization is recruiting a Disease Surveillance Officer to support Ethiopia\'s public health emergency preparedness. Responsibilities include coordinating disease surveillance systems, training health workers, and supporting outbreak response.',
      summary: 'Public health surveillance role with WHO in Ethiopia',
      type: OpportunityType.JOB,
      url: 'https://www.who.int/careers',
      applicationUrl: 'https://careers.who.int/careersection/ex/jobdetail/statExternal?pid=230100',
      applicationDeadline: future60,
      salaryMin: 5000,
      salaryMax: 8000,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 90,
      qualityScore: 80,
      overallRank: 86,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      organizationId: createdOrgs['unicef-ethiopia']?.id,
      categoryId: healthCategory?.id,
      tagSlugs: ['full-time', 'public-health', 'addis-ababa'],
    },
    {
      title: 'WFP Ethiopia - Logistics Associate',
      slug: 'wfp-ethiopia-logistics-associate',
      description: 'The World Food Programme seeks a Logistics Associate to support food assistance operations in Ethiopia. The role involves warehouse management, fleet coordination, and supply chain monitoring across field offices.',
      summary: 'Logistics role supporting food assistance in Ethiopia',
      type: OpportunityType.JOB,
      url: 'https://www.wfp.org/careers',
      applicationUrl: 'https://www.wfp.org/careers',
      applicationDeadline: future45,
      salaryMin: 4000,
      salaryMax: 6000,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 88,
      qualityScore: 78,
      overallRank: 84,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['full-time', 'logistics', 'ngo', 'addis-ababa'],
    },
    {
      title: 'UNICEF Ethiopia - Education Specialist',
      slug: 'unicef-ethiopia-education-specialist',
      description: 'UNICEF Ethiopia seeks an Education Specialist to support quality learning for children. Responsibilities include programme design, monitoring, and coordination with government partners on education policy and implementation.',
      summary: 'Education programme role with UNICEF Ethiopia',
      type: OpportunityType.JOB,
      url: 'https://www.unicef.org/ethiopia/work-us',
      applicationUrl: 'https://www.unicef.org/ethiopia/work-us',
      applicationDeadline: future60,
      salaryMin: 6000,
      salaryMax: 9000,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 92,
      qualityScore: 82,
      overallRank: 88,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      organizationId: createdOrgs['unicef-ethiopia']?.id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['full-time', 'education', 'ngo', 'addis-ababa'],
    },
    {
      title: 'Mastercard Foundation Scholars Program - AAU',
      slug: 'mastercard-scholars-program-aau-2025',
      description: 'The Mastercard Foundation Scholars Program at Addis Ababa University provides full scholarships for talented young Africans. Covers tuition, accommodation, stipend, and leadership development for undergraduate and master\'s students.',
      summary: 'Full scholarship for African students at Addis Ababa University',
      type: OpportunityType.SCHOLARSHIP,
      url: 'https://www.mastercardfdn.org/scholars',
      applicationUrl: 'https://www.mastercardfdn.org/scholars',
      applicationDeadline: future90,
      salaryMin: 0,
      salaryMax: 0,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 85,
      qualityScore: 88,
      overallRank: 86,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      organizationId: createdOrgs['world-bank-ethiopia']?.id,
      categoryId: eduCategory?.id,
      tagSlugs: ['scholarship', 'academic', 'africa', 'addis-ababa'],
    },
    {
      title: 'World Bank - Ethiopia Climate Grant Program',
      slug: 'world-bank-ethiopia-climate-grant',
      description: 'The World Bank offers grants up to $500,000 for organizations implementing climate resilience projects in Ethiopia. Focus areas include sustainable agriculture, water resource management, and renewable energy solutions.',
      summary: 'Up to $500K grants for climate projects in Ethiopia',
      type: OpportunityType.GRANT,
      url: 'https://www.worldbank.org/en/about/careers',
      applicationUrl: 'https://projects.worldbank.org/en/projects-operations/procurement',
      applicationDeadline: future120,
      salaryMin: 100000,
      salaryMax: 500000,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 94,
      qualityScore: 90,
      overallRank: 92,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      organizationId: createdOrgs['world-bank-ethiopia']?.id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['grant', 'climate', 'development', 'funding'],
    },
    {
      title: 'Safaricom Ethiopia - Mobile Money Developer',
      slug: 'safaricom-ethiopia-mobile-money-dev',
      description: 'Safaricom Ethiopia is hiring mobile money developers to build M-Pesa solutions for the Ethiopian market. Work with cutting-edge fintech stack serving millions of users across the country.',
      summary: 'Build M-Pesa mobile money solutions for Ethiopia',
      type: OpportunityType.JOB,
      url: 'https://safaricom.et/careers',
      applicationUrl: 'https://safaricom.et/careers',
      applicationDeadline: future60,
      salaryMin: 80000,
      salaryMax: 150000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 80,
      qualityScore: 75,
      overallRank: 78,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      organizationId: createdOrgs['safaricom-ethiopia']?.id,
      categoryId: techCategory?.id,
      tagSlugs: ['full-time', 'javascript', 'fintech', 'addis-ababa'],
    },
    {
      title: 'UN Jobs Ethiopia - Development Programme',
      slug: 'un-jobs-ethiopia-dev-programme',
      description: 'United Nations development programme opportunities in Ethiopia. Multiple roles available in programme management, monitoring, and field coordination across UN agencies.',
      summary: 'UN development opportunities across Ethiopia',
      type: OpportunityType.JOB,
      url: 'https://unjobs.org/countries/ethiopia',
      applicationUrl: 'https://unjobs.org/countries/ethiopia',
      applicationDeadline: future90,
      salaryMin: 4000,
      salaryMax: 10000,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 82,
      qualityScore: 72,
      overallRank: 78,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['full-time', 'monitoring-evaluation', 'ngo', 'ethiopia'],
    },
    {
      title: 'Ethiopian Airlines - Software Engineering Intern',
      slug: 'ethiopian-airlines-sw-engineering-intern',
      description: 'Ethiopian Airlines Digital Innovation team offers a 6-month internship for software engineering students. Work on real projects involving mobile apps, data analytics, and enterprise systems. Monthly stipend provided.',
      summary: '6-month paid internship in aviation technology',
      type: OpportunityType.INTERNSHIP,
      url: 'https://www.ethiopianairlines.com/careers',
      applicationUrl: 'https://www.ethiopianairlines.com/academy/apply',
      applicationDeadline: future60,
      salaryMin: 8000,
      salaryMax: 15000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 88,
      qualityScore: 80,
      overallRank: 85,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      organizationId: createdOrgs['ethiopian-airlines']?.id,
      categoryId: techCategory?.id,
      tagSlugs: ['internship', 'entry-level', 'addis-ababa', 'aviation'],
    },
    {
      title: 'UNICEF Ethiopia - WASH Internship',
      slug: 'unicef-ethiopia-wash-internship',
      description: 'UNICEF Ethiopia offers an internship in the WASH (Water, Sanitation and Hygiene) programme. Gain hands-on experience in programme support, data collection, and field monitoring in one of UNICEF\'s largest country offices.',
      summary: 'Internship in water and sanitation with UNICEF Ethiopia',
      type: OpportunityType.INTERNSHIP,
      url: 'https://www.unicef.org/ethiopia/work-us',
      applicationUrl: 'https://www.unicef.org/ethiopia/work-us',
      applicationDeadline: future45,
      salaryMin: 5000,
      salaryMax: 8000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 90,
      qualityScore: 82,
      overallRank: 87,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      organizationId: createdOrgs['unicef-ethiopia']?.id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['internship', 'entry-level', 'water-sanitation', 'addis-ababa'],
    },
    {
      title: 'Hibret Bank - Credit Officer',
      slug: 'hibret-bank-credit-officer',
      description: 'Hibret Bank SC is seeking qualified Credit Officers to assess loan applications, manage credit portfolios, and ensure timely repayment. Candidates should have a degree in finance, economics, or business administration.',
      summary: 'Credit officer role at one of Ethiopia\'s leading private banks',
      type: OpportunityType.JOB,
      url: 'https://www.hibretbank.com.et/careers',
      applicationUrl: 'https://www.hibretbank.com.et/careers',
      applicationDeadline: future30,
      salaryMin: 55000,
      salaryMax: 95000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 72,
      qualityScore: 68,
      overallRank: 70,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      categoryId: businessCategory?.id,
      tagSlugs: ['full-time', 'banking', 'finance', 'addis-ababa'],
    },
    {
      title: 'Wegagen Bank - IT Systems Analyst',
      slug: 'wegagen-bank-it-systems-analyst',
      description: 'Wegagen Bank SC invites applications for IT Systems Analyst positions. Responsible for analysing, designing, and implementing banking IT systems. Requires strong background in database management and software development.',
      summary: 'IT analyst role at Wegagen Bank',
      type: OpportunityType.JOB,
      url: 'https://www.wegagen.com/careers',
      applicationUrl: 'https://www.wegagen.com/careers',
      applicationDeadline: future45,
      salaryMin: 60000,
      salaryMax: 100000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 70,
      qualityScore: 66,
      overallRank: 68,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      categoryId: techCategory?.id,
      tagSlugs: ['full-time', 'it-systems', 'banking', 'addis-ababa'],
    },
    {
      title: 'EthioJobs - Marketing Coordinator',
      slug: 'ethiojobs-marketing-coordinator',
      description: 'Top companies in Ethiopia are hiring Marketing Coordinators to manage social media campaigns, organize events, and support brand development. Great entry-level opportunity for marketing graduates.',
      summary: 'Entry-level marketing role at top Ethiopian companies',
      type: OpportunityType.JOB,
      url: 'https://www.ethiojobs.net/',
      applicationUrl: 'https://www.ethiojobs.net/',
      applicationDeadline: future30,
      salaryMin: 35000,
      salaryMax: 60000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 65,
      qualityScore: 60,
      overallRank: 63,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      categoryId: businessCategory?.id,
      tagSlugs: ['full-time', 'marketing', 'social-media', 'addis-ababa'],
    },
    {
      title: 'Addis Fortune - Business Reporter Intern',
      slug: 'addis-fortune-reporter-intern',
      description: 'Addis Fortune, Ethiopia\'s leading business newspaper, is offering an internship for aspiring journalists. Write business stories, conduct interviews, and learn investigative journalism in a professional newsroom.',
      summary: 'Journalism internship at Ethiopia\'s top business newspaper',
      type: OpportunityType.INTERNSHIP,
      url: 'https://www.addisfortune.news/jobs',
      applicationUrl: 'https://www.addisfortune.news/jobs',
      applicationDeadline: future30,
      salaryMin: 5000,
      salaryMax: 10000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 68,
      qualityScore: 72,
      overallRank: 70,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      categoryId: businessCategory?.id,
      tagSlugs: ['internship', 'entry-level', 'journalism', 'addis-ababa'],
    },
    {
      title: 'ILO Ethiopia - Youth Employment Programme',
      slug: 'ilo-ethiopia-youth-employment',
      description: 'The International Labour Organization seeks a Youth Employment Programme Officer to support skills development and job creation initiatives for young Ethiopians. Role involves policy analysis, capacity building, and partner coordination.',
      summary: 'Youth employment programme role with ILO in Ethiopia',
      type: OpportunityType.JOB,
      url: 'https://www.ilo.org/careers',
      applicationUrl: 'https://www.ilo.org/careers',
      applicationDeadline: future60,
      salaryMin: 5000,
      salaryMax: 8500,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 84,
      qualityScore: 76,
      overallRank: 80,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['full-time', 'youth-development', 'labour', 'addis-ababa'],
    },
    {
      title: 'Ethio Telecom - Network Engineer',
      slug: 'ethio-telecom-network-engineer',
      description: 'Ethio Telecom, Ethiopia\'s national telecom provider, is recruiting Network Engineers to maintain and expand the country\'s telecommunications infrastructure. Opportunities in Addis Ababa and regional offices.',
      summary: 'Network engineering role at Ethiopia\'s national telecom',
      type: OpportunityType.JOB,
      url: 'https://www.ethiotelecom.et',
      applicationUrl: 'https://www.ethiotelecom.et',
      applicationDeadline: future45,
      salaryMin: 65000,
      salaryMax: 110000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 75,
      qualityScore: 70,
      overallRank: 73,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      organizationId: createdOrgs['ethio-telecom']?.id,
      categoryId: engCategory?.id,
      tagSlugs: ['full-time', 'telecommunications', 'networking', 'addis-ababa'],
    },
    // === MORE JOBS ===
    {
      title: 'Ethiopian Electric Power - Electrical Engineer',
      slug: 'eep-electrical-engineer',
      description: 'Ethiopian Electric Power is recruiting Electrical Engineers for the Grand Ethiopian Renaissance Dam operations team. Work on one of Africa\'s largest hydroelectric projects.',
      summary: 'Electrical engineering at Africa\'s largest hydro dam',
      type: OpportunityType.JOB,
      url: 'https://eep.gov.et',
      applicationUrl: 'https://eep.gov.et',
      applicationDeadline: future60,
      salaryMin: 70000,
      salaryMax: 130000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 76,
      qualityScore: 72,
      overallRank: 74,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      organizationId: createdOrgs['eep']?.id,
      categoryId: engCategory?.id,
      tagSlugs: ['full-time', 'engineering', 'energy', 'bahirdar'],
    },
    {
      title: 'Dashen Bank - Branch Manager',
      slug: 'dashen-bank-branch-manager',
      description: 'Dashen Bank SC seeks experienced banking professionals for Branch Manager positions across Ethiopia. Lead branch operations, manage teams, and drive business growth.',
      summary: 'Branch manager positions across Ethiopia',
      type: OpportunityType.JOB,
      url: 'https://www.dashenbanksc.com',
      applicationUrl: 'https://www.dashenbanksc.com',
      applicationDeadline: future45,
      salaryMin: 80000,
      salaryMax: 140000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 68,
      qualityScore: 64,
      overallRank: 66,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      organizationId: createdOrgs['dashen-bank']?.id,
      categoryId: businessCategory?.id,
      tagSlugs: ['full-time', 'banking', 'management', 'addis-ababa'],
    },
    {
      title: 'Awash Bank - Risk Analyst',
      slug: 'awash-bank-risk-analyst',
      description: 'Awash Bank invites applications for Risk Analyst positions. Analyse credit, market, and operational risks. Develop risk models and support regulatory compliance.',
      summary: 'Risk analysis at one of Ethiopia\'s pioneer banks',
      type: OpportunityType.JOB,
      url: 'https://www.awashbank.com',
      applicationUrl: 'https://www.awashbank.com',
      applicationDeadline: future30,
      salaryMin: 65000,
      salaryMax: 110000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 66,
      qualityScore: 62,
      overallRank: 64,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      organizationId: createdOrgs['awash-bank']?.id,
      categoryId: businessCategory?.id,
      tagSlugs: ['full-time', 'risk-management', 'banking', 'addis-ababa'],
    },
    {
      title: 'Zemen Bank - Customer Service Officer',
      slug: 'zemen-bank-customer-service',
      description: 'Zemen Bank is recruiting Customer Service Officers to provide excellent service to banking clients. Handle inquiries, resolve complaints, and promote banking products.',
      summary: 'Customer service roles at Zemen Bank',
      type: OpportunityType.JOB,
      url: 'https://www.zemenbank.com/careers',
      applicationUrl: 'https://www.zemenbank.com/careers',
      applicationDeadline: future30,
      salaryMin: 35000,
      salaryMax: 55000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 62,
      qualityScore: 58,
      overallRank: 60,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      categoryId: businessCategory?.id,
      tagSlugs: ['full-time', 'customer-service', 'banking', 'addis-ababa'],
    },
    {
      title: 'NRC Ethiopia - Protection Officer',
      slug: 'nrc-ethiopia-protection-officer',
      description: 'Norwegian Refugee Council is recruiting a Protection Officer for Ethiopian refugee response. Provide legal aid, case management, and protection monitoring for displaced populations.',
      summary: 'Protection and legal aid for refugees in Ethiopia',
      type: OpportunityType.JOB,
      url: 'https://www.nrc.no/careers',
      applicationUrl: 'https://www.nrc.no/careers',
      applicationDeadline: future45,
      salaryMin: 4500,
      salaryMax: 7000,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 82,
      qualityScore: 78,
      overallRank: 80,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['full-time', 'protection', 'refugees', 'addis-ababa'],
    },
    {
      title: 'IRC Ethiopia - Programme Manager',
      slug: 'irc-ethiopia-programme-manager',
      description: 'International Rescue Committee seeks a Programme Manager for health and nutrition programmes in Somali Region. Oversee implementation, budgeting, and team coordination.',
      summary: 'Programme management in health and nutrition',
      type: OpportunityType.JOB,
      url: 'https://www.rescue.org/careers',
      applicationUrl: 'https://www.rescue.org/careers',
      applicationDeadline: future60,
      salaryMin: 5500,
      salaryMax: 8500,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 84,
      qualityScore: 80,
      overallRank: 82,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['full-time', 'programme-management', 'health', 'somali-region'],
    },
    {
      title: 'World Vision Ethiopia - Water Engineer',
      slug: 'world-vision-ethiopia-water-engineer',
      description: 'World Vision Ethiopia is seeking a Water Engineer to design and implement WASH projects. Supervise borehole drilling, piped water systems, and community water points.',
      summary: 'Water engineering for rural communities',
      type: OpportunityType.JOB,
      url: 'https://www.worldvision.org/careers',
      applicationUrl: 'https://www.worldvision.org/careers',
      applicationDeadline: future45,
      salaryMin: 5000,
      salaryMax: 7500,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 80,
      qualityScore: 76,
      overallRank: 78,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['full-time', 'water-sanitation', 'engineering', 'rural'],
    },
    {
      title: 'CARE Ethiopia - Gender Advisor',
      slug: 'care-ethiopia-gender-advisor',
      description: 'CARE International seeks a Gender Advisor to mainstream gender across all programmes in Ethiopia. Develop gender strategies, conduct assessments, and train staff.',
      summary: 'Gender mainstreaming across development programmes',
      type: OpportunityType.JOB,
      url: 'https://www.care.org/careers',
      applicationUrl: 'https://www.care.org/careers',
      applicationDeadline: future60,
      salaryMin: 5000,
      salaryMax: 7500,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 78,
      qualityScore: 74,
      overallRank: 76,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['full-time', 'gender', 'development', 'addis-ababa'],
    },
    {
      title: 'Plan International Ethiopia - MEAL Officer',
      slug: 'plan-international-ethiopia-meal',
      description: 'Plan International is recruiting a MEAL Officer to strengthen monitoring, evaluation, accountability, and learning systems for child-focused programmes.',
      summary: 'MEAL systems for children\'s programmes',
      type: OpportunityType.JOB,
      url: 'https://www.plan-international.org/careers',
      applicationUrl: 'https://www.plan-international.org/careers',
      applicationDeadline: future45,
      salaryMin: 4000,
      salaryMax: 6500,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 76,
      qualityScore: 72,
      overallRank: 74,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['full-time', 'monitoring-evaluation', 'children', 'addis-ababa'],
    },
    {
      title: 'Mercy Corps Ethiopia - Finance Manager',
      slug: 'mercy-corps-ethiopia-finance',
      description: 'Mercy Corps seeks a Finance Manager to oversee financial operations for multi-million dollar programmes. Manage budgets, reporting, and compliance with donor requirements.',
      summary: 'Financial management for large-scale programmes',
      type: OpportunityType.JOB,
      url: 'https://www.mercycorps.org/careers',
      applicationUrl: 'https://www.mercycorps.org/careers',
      applicationDeadline: future60,
      salaryMin: 6000,
      salaryMax: 9000,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 80,
      qualityScore: 76,
      overallRank: 78,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['full-time', 'finance', 'management', 'addis-ababa'],
    },
    // === MORE INTERNSHIPS ===
    {
      title: 'UNDP Ethiopia - Data Analytics Intern',
      slug: 'undp-ethiopia-data-analytics-intern',
      description: 'UNDP Ethiopia offers a 3-month internship in data analytics. Work with programme data, create dashboards, and support evidence-based decision making.',
      summary: 'Data analytics internship with UNDP Ethiopia',
      type: OpportunityType.INTERNSHIP,
      url: 'https://www.undp.org/ethiopia',
      applicationUrl: 'https://www.undp.org/ethiopia',
      applicationDeadline: future30,
      salaryMin: 5000,
      salaryMax: 8000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 82,
      qualityScore: 75,
      overallRank: 79,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['internship', 'entry-level', 'data-analytics', 'addis-ababa'],
    },
    {
      title: 'WHO Ethiopia - Research Intern',
      slug: 'who-ethiopia-research-intern',
      description: 'WHO Ethiopia offers research internships in epidemiology and public health. Assist with literature reviews, data analysis, and report writing for disease surveillance.',
      summary: 'Public health research internship with WHO',
      type: OpportunityType.INTERNSHIP,
      url: 'https://www.who.int/careers',
      applicationUrl: 'https://careers.who.int',
      applicationDeadline: future45,
      salaryMin: 4000,
      salaryMax: 7000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 86,
      qualityScore: 78,
      overallRank: 82,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: healthCategory?.id,
      tagSlugs: ['internship', 'entry-level', 'research', 'addis-ababa'],
    },
    {
      title: 'Safaricom Ethiopia - Marketing Intern',
      slug: 'safaricom-ethiopia-marketing-intern',
      description: 'Safaricom Ethiopia offers a marketing internship. Support social media campaigns, market research, and brand promotion for one of Ethiopia\'s top telecom brands.',
      summary: 'Marketing internship at Safaricom Ethiopia',
      type: OpportunityType.INTERNSHIP,
      url: 'https://safaricom.et/careers',
      applicationUrl: 'https://safaricom.et/careers',
      applicationDeadline: future30,
      salaryMin: 6000,
      salaryMax: 10000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 74,
      qualityScore: 68,
      overallRank: 71,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      organizationId: createdOrgs['safaricom-ethiopia']?.id,
      categoryId: techCategory?.id,
      tagSlugs: ['internship', 'entry-level', 'marketing', 'addis-ababa'],
    },
    {
      title: 'Ethio Telecom - Finance Intern',
      slug: 'ethio-telecom-finance-intern',
      description: 'Ethio Telecom offers a finance internship for accounting and finance students. Assist with accounts payable, reconciliation, and financial reporting.',
      summary: 'Finance internship at Ethiopia\'s national telecom',
      type: OpportunityType.INTERNSHIP,
      url: 'https://www.ethiotelecom.et',
      applicationUrl: 'https://www.ethiotelecom.et',
      applicationDeadline: future30,
      salaryMin: 5000,
      salaryMax: 8000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 70,
      qualityScore: 65,
      overallRank: 68,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      organizationId: createdOrgs['ethio-telecom']?.id,
      categoryId: businessCategory?.id,
      tagSlugs: ['internship', 'entry-level', 'finance', 'addis-ababa'],
    },
    {
      title: 'CBE - Human Resources Intern',
      slug: 'cbe-hr-intern',
      description: 'Commercial Bank of Ethiopia offers HR internships. Support recruitment, onboarding, and employee records management at Ethiopia\'s largest bank.',
      summary: 'HR internship at Commercial Bank of Ethiopia',
      type: OpportunityType.INTERNSHIP,
      url: 'https://www.combanketh.et',
      applicationUrl: 'https://www.combanketh.et',
      applicationDeadline: future30,
      salaryMin: 4000,
      salaryMax: 7000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 65,
      qualityScore: 60,
      overallRank: 63,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      organizationId: createdOrgs['cbe']?.id,
      categoryId: businessCategory?.id,
      tagSlugs: ['internship', 'entry-level', 'human-resources', 'addis-ababa'],
    },
    {
      title: 'Addis Ababa University - Research Intern',
      slug: 'aau-research-intern',
      description: 'Addis Ababa University Department of Computer Science offers research internships. Assist faculty with machine learning and AI research projects.',
      summary: 'AI/ML research internship at AAU',
      type: OpportunityType.INTERNSHIP,
      url: 'https://www.aau.edu.et',
      applicationUrl: 'https://www.aau.edu.et',
      applicationDeadline: future45,
      salaryMin: 3000,
      salaryMax: 5000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 72,
      qualityScore: 68,
      overallRank: 70,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      categoryId: eduCategory?.id,
      tagSlugs: ['internship', 'entry-level', 'research', 'addis-ababa'],
    },
    {
      title: 'WFP Ethiopia - Logistics Intern',
      slug: 'wfp-ethiopia-logistics-intern',
      description: 'WFP Ethiopia offers logistics internships. Support supply chain operations, fleet management, and warehouse coordination for food assistance programmes.',
      summary: 'Logistics internship supporting food assistance',
      type: OpportunityType.INTERNSHIP,
      url: 'https://www.wfp.org/careers',
      applicationUrl: 'https://www.wfp.org/careers',
      applicationDeadline: future45,
      salaryMin: 4000,
      salaryMax: 6000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 84,
      qualityScore: 76,
      overallRank: 80,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['internship', 'entry-level', 'logistics', 'addis-ababa'],
    },
    // === MORE SCHOLARSHIPS ===
    {
      title: 'DAAD Scholarship - Study in Germany',
      slug: 'daad-scholarship-germany',
      description: 'DAAD (German Academic Exchange Service) offers fully funded scholarships for Ethiopian students to pursue masters and PhD programmes at German universities. Covers tuition, living expenses, and travel.',
      summary: 'Fully funded study in Germany for Ethiopian students',
      type: OpportunityType.SCHOLARSHIP,
      url: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/',
      applicationUrl: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/',
      applicationDeadline: future90,
      salaryMin: 0,
      salaryMax: 0,
      salaryCurrency: 'EUR',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 88,
      qualityScore: 85,
      overallRank: 87,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: eduCategory?.id,
      tagSlugs: ['scholarship', 'academic', 'germany', 'international'],
    },
    {
      title: 'Fulbright Scholarship - Study in USA',
      slug: 'fulbright-scholarship-usa',
      description: 'Fulbright Foreign Student Programme offers scholarships for Ethiopian professionals and graduates to study in the United States. Fully funded including tuition, airfare, and living allowance.',
      summary: 'Fully funded study in the USA',
      type: OpportunityType.SCHOLARSHIP,
      url: 'https://www.fulbright.org/',
      applicationUrl: 'https://www.fulbright.org/',
      applicationDeadline: future120,
      salaryMin: 0,
      salaryMax: 0,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 92,
      qualityScore: 90,
      overallRank: 91,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: eduCategory?.id,
      tagSlugs: ['scholarship', 'academic', 'usa', 'international'],
    },
    {
      title: 'Korean Government Scholarship - KGSP',
      slug: 'kgsp-scholarship-korea',
      description: 'Korean Government Scholarship Programme offers fully funded scholarships for Ethiopian students to study at Korean universities. Includes tuition, stipend, airfare, and Korean language training.',
      summary: 'Fully funded study in South Korea',
      type: OpportunityType.SCHOLARSHIP,
      url: 'https://www.studyinkorea.go.kr/',
      applicationUrl: 'https://www.studyinkorea.go.kr/',
      applicationDeadline: future90,
      salaryMin: 0,
      salaryMax: 0,
      salaryCurrency: 'KRW',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 86,
      qualityScore: 82,
      overallRank: 84,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: eduCategory?.id,
      tagSlugs: ['scholarship', 'academic', 'south-korea', 'international'],
    },
    {
      title: 'JICA Scholarship - Study in Japan',
      slug: 'jica-scholarship-japan',
      description: 'Japan International Cooperation Agency offers scholarships for Ethiopian mid-career professionals. Study at Japanese universities with full funding including tuition and living expenses.',
      summary: 'Fully funded professional development in Japan',
      type: OpportunityType.SCHOLARSHIP,
      url: 'https://www.jasso.go.jp/en/',
      applicationUrl: 'https://www.jasso.go.jp/en/',
      applicationDeadline: future90,
      salaryMin: 0,
      salaryMax: 0,
      salaryCurrency: 'JPY',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 84,
      qualityScore: 80,
      overallRank: 82,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: eduCategory?.id,
      tagSlugs: ['scholarship', 'academic', 'japan', 'international'],
    },
    {
      title: 'Ethiopian Government - Ethiopian Higher Education Scholarship',
      slug: 'ethiopia-he Scholarship',
      description: 'The Ethiopian Ministry of Education offers scholarships for outstanding students to pursue undergraduate and graduate studies at top Ethiopian universities. Merit-based with living stipend.',
      summary: 'Government-funded scholarships at Ethiopian universities',
      type: OpportunityType.SCHOLARSHIP,
      url: 'https://www.moe.gov.et',
      applicationUrl: 'https://www.moe.gov.et',
      applicationDeadline: future60,
      salaryMin: 0,
      salaryMax: 0,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 75,
      qualityScore: 70,
      overallRank: 73,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      categoryId: eduCategory?.id,
      tagSlugs: ['scholarship', 'academic', 'government', 'ethiopia'],
    },
    {
      title: 'Addis Ababa University - Graduate Assistantship',
      slug: 'aau-graduate-assistantship',
      description: 'Addis Ababa University offers graduate assistantships for master\'s and PhD students. Receive stipend while gaining teaching and research experience.',
      summary: 'Teaching and research positions for graduate students',
      type: OpportunityType.SCHOLARSHIP,
      url: 'https://www.aau.edu.et',
      applicationUrl: 'https://www.aau.edu.et',
      applicationDeadline: future45,
      salaryMin: 8000,
      salaryMax: 15000,
      salaryCurrency: 'ETB',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 72,
      qualityScore: 68,
      overallRank: 70,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      categoryId: eduCategory?.id,
      tagSlugs: ['scholarship', 'academic', 'research', 'addis-ababa'],
    },
    // === MORE GRANTS ===
    {
      title: 'NRC Ethiopia - Humanitarian Innovation Grant',
      slug: 'nrc-humanitarian-innovation-grant',
      description: 'Norwegian Refugee Council offers grants up to $200,000 for innovative humanitarian solutions in Ethiopia. Focus on shelter, education, and livelihood programmes.',
      summary: 'Grants for innovative humanitarian solutions',
      type: OpportunityType.GRANT,
      url: 'https://www.nrc.no/careers',
      applicationUrl: 'https://www.nrc.no/careers',
      applicationDeadline: future90,
      salaryMin: 50000,
      salaryMax: 200000,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 80,
      qualityScore: 75,
      overallRank: 78,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['grant', 'humanitarian', 'innovation', 'funding'],
    },
    {
      title: 'IRC Ethiopia - Community Resilience Fund',
      slug: 'irc-community-resilience-fund',
      description: 'International Rescue Community Fund supports community-based organizations in Ethiopia with grants up to $100,000 for resilience-building projects.',
      summary: 'Community grants for resilience projects',
      type: OpportunityType.GRANT,
      url: 'https://www.rescue.org/careers',
      applicationUrl: 'https://www.rescue.org/careers',
      applicationDeadline: future60,
      salaryMin: 20000,
      salaryMax: 100000,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 78,
      qualityScore: 72,
      overallRank: 75,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['grant', 'community', 'resilience', 'funding'],
    },
    {
      title: 'World Vision Ethiopia - Child Protection Fund',
      slug: 'world-vision-child-protection-fund',
      description: 'World Vision offers grants for organizations working on child protection in Ethiopia. Projects should address child labour, early marriage, and violence against children.',
      summary: 'Funding for child protection projects',
      type: OpportunityType.GRANT,
      url: 'https://www.worldvision.org/careers',
      applicationUrl: 'https://www.worldvision.org/careers',
      applicationDeadline: future90,
      salaryMin: 30000,
      salaryMax: 150000,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 76,
      qualityScore: 70,
      overallRank: 73,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['grant', 'child-protection', 'social-development', 'funding'],
    },
    {
      title: 'CARE Ethiopia - Women\'s Empowerment Grant',
      slug: 'care-womens-empowerment-grant',
      description: 'CARE International offers grants for organizations advancing women\'s economic empowerment in Ethiopia. Focus on financial inclusion, market access, and leadership development.',
      summary: 'Grants for women\'s economic empowerment',
      type: OpportunityType.GRANT,
      url: 'https://www.care.org/careers',
      applicationUrl: 'https://www.care.org/careers',
      applicationDeadline: future60,
      salaryMin: 25000,
      salaryMax: 120000,
      salaryCurrency: 'USD',
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 74,
      qualityScore: 68,
      overallRank: 71,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['grant', 'gender', 'empowerment', 'funding'],
    },
    // === MORE TRAINING ===
    {
      title: 'Ethio Telecom - 5G Technology Training',
      slug: 'ethio-telecom-5g-training',
      description: 'Ethio Telecom offers a 6-week intensive training programme on 5G network deployment and management. Learn from international telecom experts.',
      summary: '5G technology certification programme',
      type: OpportunityType.TRAINING,
      url: 'https://www.ethiotelecom.et',
      applicationUrl: 'https://www.ethiotelecom.et',
      applicationDeadline: future45,
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 72,
      qualityScore: 68,
      overallRank: 70,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      organizationId: createdOrgs['ethio-telecom']?.id,
      categoryId: techCategory?.id,
      tagSlugs: ['training', 'capacity-building', 'telecommunications', 'addis-ababa'],
    },
    {
      title: 'Safaricom Ethiopia - Cybersecurity Bootcamp',
      slug: 'safaricom-cybersecurity-bootcamp',
      description: 'Safaricom Ethiopia partners with cybersecurity firms to offer a 4-week bootcamp. Learn ethical hacking, network security, and incident response.',
      summary: 'Cybersecurity skills bootcamp',
      type: OpportunityType.TRAINING,
      url: 'https://safaricom.et/careers',
      applicationUrl: 'https://safaricom.et/careers',
      applicationDeadline: future30,
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 76,
      qualityScore: 72,
      overallRank: 74,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      organizationId: createdOrgs['safaricom-ethiopia']?.id,
      categoryId: techCategory?.id,
      tagSlugs: ['training', 'capacity-building', 'cybersecurity', 'addis-ababa'],
    },
    {
      title: 'Addis Ababa University - Data Science Bootcamp',
      slug: 'aau-data-science-bootcamp',
      description: 'AAU School of Data Science offers an 8-week intensive bootcamp. Cover Python, machine learning, and real-world data projects with industry partners.',
      summary: 'Data science bootcamp at Addis Ababa University',
      type: OpportunityType.TRAINING,
      url: 'https://www.aau.edu.et',
      applicationUrl: 'https://www.aau.edu.et',
      applicationDeadline: future45,
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 78,
      qualityScore: 74,
      overallRank: 76,
      lastLinkCheck: now,
      sourceId: createdSources[0].id,
      categoryId: techCategory?.id,
      tagSlugs: ['training', 'capacity-building', 'data-science', 'addis-ababa'],
    },
    // === MORE VOLUNTEER ===
    {
      title: 'Peace Corps Ethiopia - Teaching Volunteer',
      slug: 'peace-corps-ethiopia-teaching',
      description: 'Peace Corps Ethiopia recruits volunteers to teach English in rural schools. 27-month commitment with full support, training, and living stipend.',
      summary: 'Teach English in rural Ethiopian communities',
      type: OpportunityType.VOLUNTEER,
      url: 'https://www.peacecorps.gov/',
      applicationUrl: 'https://www.peacecorps.gov/',
      applicationDeadline: future90,
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 85,
      qualityScore: 82,
      overallRank: 84,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: eduCategory?.id,
      tagSlugs: ['volunteer', 'community-development', 'teaching', 'rural'],
    },
    {
      title: 'UN Volunteers Ethiopia - Community Developer',
      slug: 'unv-ethiopia-community-developer',
      description: 'UN Volunteers programme seeks community developers for grassroots projects in Ethiopia. Support sustainable development in rural communities.',
      summary: 'Community development volunteering with UN',
      type: OpportunityType.VOLUNTEER,
      url: 'https://www.unv.org/',
      applicationUrl: 'https://www.unv.org/',
      applicationDeadline: future60,
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 82,
      qualityScore: 78,
      overallRank: 80,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['volunteer', 'community-development', 'sustainable-development', 'rural'],
    },
    {
      title: 'VSO Ethiopia - Health Volunteer',
      slug: 'vso-ethiopia-health-volunteer',
      description: 'VSO International recruits health volunteers to work in Ethiopian health centres. Support maternal and child health, HIV/AIDS, and community health programmes.',
      summary: 'Health volunteering in Ethiopian communities',
      type: OpportunityType.VOLUNTEER,
      url: 'https://www.vsointernational.org/',
      applicationUrl: 'https://www.vsointernational.org/',
      applicationDeadline: future90,
      isRemote: false,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 80,
      qualityScore: 76,
      overallRank: 78,
      lastLinkCheck: now,
      sourceId: createdSources[1].id,
      categoryId: healthCategory?.id,
      tagSlugs: ['volunteer', 'health', 'community-development', 'rural'],
    },
    // === MORE REMOTE WORK ===
    {
      title: 'Remote Software Developer - African Startup',
      slug: 'remote-sw-dev-african-startup',
      description: 'Fast-growing African tech startup hiring remote software developers based in Ethiopia. Build mobile apps and web platforms using React Native and Node.js. Competitive USD salary.',
      summary: 'Remote dev role at African startup, paid in USD',
      type: OpportunityType.REMOTE_WORK,
      url: 'https://www.linkedin.com/jobs/search/?keywords=remote+developer&location=Ethiopia',
      applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=remote+developer&location=Ethiopia',
      applicationDeadline: future60,
      salaryMin: 2000,
      salaryMax: 5000,
      salaryCurrency: 'USD',
      isRemote: true,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 70,
      qualityScore: 65,
      overallRank: 68,
      lastLinkCheck: now,
      sourceId: createdSources[2].id,
      categoryId: techCategory?.id,
      tagSlugs: ['remote', 'full-time', 'javascript', 'africa'],
    },
    {
      title: 'Remote Data Analyst - Global NGO',
      slug: 'remote-data-analyst-global-ngo',
      description: 'International NGO seeks remote data analysts based in Ethiopia. Analyse programme data, create visualizations, and support evidence-based decision making across African programmes.',
      summary: 'Remote data analysis for international programmes',
      type: OpportunityType.REMOTE_WORK,
      url: 'https://www.linkedin.com/jobs/search/?keywords=data+analyst&location=Ethiopia',
      applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=data+analyst&location=Ethiopia',
      applicationDeadline: future45,
      salaryMin: 1500,
      salaryMax: 3500,
      salaryCurrency: 'USD',
      isRemote: true,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 72,
      qualityScore: 68,
      overallRank: 70,
      lastLinkCheck: now,
      sourceId: createdSources[2].id,
      categoryId: ngoCategory?.id,
      tagSlugs: ['remote', 'full-time', 'data-analytics', 'ngo'],
    },
    {
      title: 'Remote Content Writer - Tech Company',
      slug: 'remote-content-writer-tech',
      description: 'Global tech company hiring remote content writers based in Africa. Write technical documentation, blog posts, and marketing content for SaaS products.',
      summary: 'Remote writing for global tech company',
      type: OpportunityType.REMOTE_WORK,
      url: 'https://www.linkedin.com/jobs/search/?keywords=content+writer&location=Ethiopia',
      applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=content+writer&location=Ethiopia',
      applicationDeadline: future30,
      salaryMin: 800,
      salaryMax: 2000,
      salaryCurrency: 'USD',
      isRemote: true,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 65,
      qualityScore: 60,
      overallRank: 63,
      lastLinkCheck: now,
      sourceId: createdSources[2].id,
      categoryId: techCategory?.id,
      tagSlugs: ['remote', 'part-time', 'content-writing', 'tech'],
    },
    {
      title: 'Remote Virtual Assistant - Global Company',
      slug: 'remote-virtual-assistant',
      description: 'International company seeks remote virtual assistants from Ethiopia. Manage calendars, handle correspondence, and support executive operations. Flexible hours.',
      summary: 'Remote virtual assistant for international company',
      type: OpportunityType.REMOTE_WORK,
      url: 'https://www.linkedin.com/jobs/search/?keywords=virtual+assistant&location=Ethiopia',
      applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=virtual+assistant&location=Ethiopia',
      applicationDeadline: future30,
      salaryMin: 500,
      salaryMax: 1200,
      salaryCurrency: 'USD',
      isRemote: true,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 62,
      qualityScore: 58,
      overallRank: 60,
      lastLinkCheck: now,
      sourceId: createdSources[2].id,
      categoryId: businessCategory?.id,
      tagSlugs: ['remote', 'part-time', 'virtual-assistant', 'admin'],
    },
    {
      title: 'Remote Graphic Designer - Marketing Agency',
      slug: 'remote-graphic-designer',
      description: 'Marketing agency hiring remote graphic designers from Ethiopia. Create social media graphics, logos, and marketing materials. Portfolio required.',
      summary: 'Remote design work for marketing agency',
      type: OpportunityType.REMOTE_WORK,
      url: 'https://www.linkedin.com/jobs/search/?keywords=graphic+designer&location=Ethiopia',
      applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=graphic+designer&location=Ethiopia',
      applicationDeadline: future30,
      salaryMin: 600,
      salaryMax: 1500,
      salaryCurrency: 'USD',
      isRemote: true,
      linkStatus: 'valid',
      linkResponseCode: 200,
      trustScore: 60,
      qualityScore: 55,
      overallRank: 58,
      lastLinkCheck: now,
      sourceId: createdSources[2].id,
      categoryId: techCategory?.id,
      tagSlugs: ['remote', 'part-time', 'graphic-design', 'creative'],
    },
  ];

  for (const opp of opportunities) {
    const { tagSlugs, ...createData } = opp as any;
    const orgId = createData.organizationId || createdOrgs['eic']?.id;

    const created = await prisma.opportunity.upsert({
      where: { slug: createData.slug },
      update: {},
      create: {
        ...createData,
        organizationId: orgId,
        categoryId: createData.categoryId || businessCategory?.id,
      },
    });

    // Add tags (diverse per opportunity)
    const oppTags = tagSlugs || tagsByType[createData.type] || ['ethiopia'];
    for (const tagSlug of oppTags) {
      const tag = await prisma.tag.findUnique({ where: { slug: tagSlug } });
      if (tag) {
        await prisma.opportunityTag.upsert({
          where: { opportunityId_tagId: { opportunityId: created.id, tagId: tag.id } },
          update: {},
          create: { opportunityId: created.id, tagId: tag.id },
        }).catch(() => {});
      }
    }

    // Add locations
    if (opp.isRemote && remoteLoc) {
      await prisma.opportunityLocation.upsert({
        where: { opportunityId_locationId: { opportunityId: created.id, locationId: remoteLoc.id } },
        update: {},
        create: { opportunityId: created.id, locationId: remoteLoc.id },
      }).catch(() => {});
    } else if (addisLoc) {
      await prisma.opportunityLocation.upsert({
        where: { opportunityId_locationId: { opportunityId: created.id, locationId: addisLoc.id } },
        update: {},
        create: { opportunityId: created.id, locationId: addisLoc.id },
      }).catch(() => {});
    }
  }
  console.log('✅ Opportunities created');

  // Create system settings
  const settings = [
    { key: 'site.name', value: 'OpportunityHub Ethiopia', category: 'general', description: 'Platform name' },
    { key: 'site.description', value: 'Ethiopia\'s #1 Free Opportunity Discovery Platform', category: 'general', description: 'Platform description' },
    { key: 'site.url', value: 'https://opportunityhub.et', category: 'general', description: 'Platform URL' },
    { key: 'site.country', value: 'Ethiopia', category: 'general', description: 'Primary country' },
    { key: 'site.currency', value: 'ETB', category: 'general', description: 'Default currency' },
    { key: 'registration.enabled', value: true, category: 'auth', description: 'Enable user registration' },
    { key: 'pricing.free', value: true, category: 'pricing', description: 'Platform is completely free' },
  ];

  for (const setting of settings) {
    await prisma.systemSetting.upsert({
      where: { key: setting.key },
      update: {},
      create: setting,
    });
  }
  console.log('✅ System settings created');

  console.log('\n🎉 OpportunityHub Ethiopia seeded successfully!');
  console.log('\n📧 Login credentials:');
  console.log('   Admin: admin@opportunityhub.et / Admin123!');
  console.log('   User:  demo@opportunityhub.et / User123!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
